"""Sparql Enpoint Adresse hinzugefügt

Revision ID: 9d60b497f3ea
Revises: f7cef3fa1d1a
Create Date: 2018-05-18 11:52:29.925373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d60b497f3ea'
down_revision = 'f7cef3fa1d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sparql', sa.Column('sparql_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sparql', 'sparql_url')
    # ### end Alembic commands ###
