"""python script for parameters

Revision ID: f7cef3fa1d1a
Revises: b20d525037dd
Create Date: 2018-05-14 00:09:02.802248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cef3fa1d1a'
down_revision = 'b20d525037dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameter', sa.Column('pythonscript', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameter', 'pythonscript')
    # ### end Alembic commands ###
